title: "Settings"
rows: 3
empty: BLACK_STAINED_GLASS_PANE
items:
  11:
    click-event: "party_change_name"
    material: NAME_TAG
    name: "Change party name"
    lore:
      - "<dark_gray>»</dark_gray> {party-name}"
  12:
    click-event: "party_change_tag"
    material: NAME_TAG
    name: "Change party tag"
    lore:
      - "<dark_gray>»</dark_gray> {party-tag}"
  13:
    click-event: "party_change_desc"
    material: PAPER
    name: "Change party description"
    lore:
      - "<dark_gray>»</dark_gray> {party-desc}"
  14:
    click-event: "party_change_motd"
    material: BELL
    name: "Change party motd"
    lore:
      - "<dark_gray>»</dark_gray> {party-motd}"
  15:
    click-event: "party_change_color"
    material: RED_DYE
    name: "Change party color"
    lore:
      - "Current <dark_gray>»</dark_gray> {party-color-code}{party-name}"
      - "Next <dark_gray>»</dark_gray> {party-next-color-code}{party-name}"
  22:
    click-event: "gui_back"
    material: DARK_OAK_DOOR
    name: "⮬ Back"
