title: "Settings"
rows: 3
empty: BLACK_STAINED_GLASS_PANE
items:
  11:
    click-event: "party_change_name"
    material: NAME_TAG
    name: "<red>◇</red> Name"
    lore:
      - "<gray>Change the party name</gray>"
      - "<dark_gray>»</dark_gray> {party-name}"
  12:
    click-event: "party_change_tag"
    material: NAME_TAG
    name: "<red>◇</red> Tag"
    lore:
      - "<gray>Change the party tag</gray>"
      - "<dark_gray>»</dark_gray> {party-tag}"
  13:
    click-event: "party_change_desc"
    material: PAPER
    name: "<red>◇</red> Description"
    lore:
      - "<gray>Change the party description</gray>"
      - "<dark_gray>»</dark_gray> {party-desc}"
  14:
    click-event: "party_change_motd"
    material: BELL
    name: "<red>◇</red> MOTD"
    lore:
      - "<gray>Change the party MOTD</gray>"
      - "<dark_gray>»</dark_gray> {party-motd}"
  15:
    click-event: "party_change_color"
    material: RED_DYE
    name: "<red>◇</red> Color"
    lore:
      - "<gray>Change the party color</gray>"
      - "<dark_gray>»</dark_gray> {party-color-code}{party-name}"
      - ""
      - "Next <dark_gray>»</dark_gray> {party-next-color-code}{party-name}"
  22:
    click-event: "gui_back"
    material: DARK_OAK_DOOR
    name: "<blue>⮬</blue> Back"
