title: "Settings"
rows: 3
empty: BLACK_STAINED_GLASS_PANE
items:
  10:
    click-event: "party_change_name"
    material: NAME_TAG
    name: "Change party name"
    lore:
      - "<dark_gray>»</dark_gray> {party-name}"
  11:
    click-event: "party_change_tag"
    material: NAME_TAG
    name: "Change party tag"
    lore:
      - "<dark_gray>»</dark_gray> {party-tag}"
  12:
    click-event: "party_change_desc"
    material: PAPER
    name: "Change party description"
    lore:
      - "<dark_gray>»</dark_gray> {party-desc}"
  13:
    click-event: "party_change_motd"
    material: BELL
    name: "Change party motd"
    lore:
      - "<dark_gray>»</dark_gray> {party-motd}"
  14:
    click-event: "party_change_color"
    material: RED_DYE
    name: "Change party color"
    lore:
      - "<dark_gray>»</dark_gray> {party-color-code}{party-name}"
      - "<dark_gray>»</dark_gray> {party-color-code}{party-tag}"
  16:
    click-event: "party_change_home"
    material: ENDER_EYE
    name: "Change party home"
  22:
    click-event: "gui_back"
    material: DARK_OAK_DOOR
    name: "⮬ Back"
