parties-commands: # Enter the main plugin commands if you changed it
  party: "party"
  sub-commands:
    color: "color"
    home: "home"
    motd: "motd"
    rename: "rename"
    tag: "tag"
  misc-commands:
    remove: "remove"
commands:
  partygui:
    command: "partygui"
    description: "Open the party GUI"
    aliases: []
  partyguia:
    command: "partyguia"
    description: "Admin command"
    aliases: []
click-sound:
  sound: block.lever.click
  volume: 1.0
  pitch: 1.0
  category: PLAYER
