parties-commands: # Enter the main plugin commands if you changed it
  party: "party"
  sub-commands:
    color: "color"
    home: "home"
    invite: "invite"
    motd: "motd"
    rename: "rename"
    tag: "tag"
  misc-commands:
    remove: "remove"
commands:
  partygui:
    command: "partygui"
    aliases: []
  partyguia:
    command: "partyguia"
    aliases: []
click-sound:
  sound: block.lever.click
  volume: 1.0
  pitch: 1.2
  category: PLAYER
max-lore-line-length: 40
decimal-format: "%.2f"